### PR TITLE
4

### PR DESCRIPTION
**Pull request by twof**

### CODE REVIEW

**Comment by carlostrianag** [comment]
Is this already working with Vapor 4?

**Comment by simonedelmann** [comment]
I am not the maintainer of this project, but I wrote a similar package compatible with Vapor 4: https://github.com/simonedelmann/crud-kit

**Comment by twof** [comment]
I don't remember what state this is in, but it probably doesn't build at the moment. I got stuck implementing recursive relations ie a model has a parent which has siblings which have children.

Other people should feel free to pick up where I left off, and @simonedelmann 's library looks great as an alternative.

**Comment by simonedelmann** [comment]
@twof Back then I only made my version of a Crud Router because of this PR not being ready. 
I just noticed you are working on this again! I would be happy to deprecate my package, if this one is actively maintained again!

**Comment by twof** [comment]
@simonedelmann I have some time this morning, so I'll see if I can get this working again. I'll let you know! Your project also has a lot of features that mine doesn't, so if I can get this working again, maybe we can find a way to combine them.

**Comment by twof** [comment]
Recursive relations are giving me trouble again, but I'm more confident that I can sort it out this time around. Swift's errors around generic type mismatches have improved dramatically.

**Comment by twof** [comment]
Alright we're looking good. I'm going to get all public APIs nice and documented and then I'll tag a release!

**Comment by twof** [comment]
I'm gonna tag a release. We've got the relevant public methods documented now. @simonedelmann I'll see if my work can be added to your library at some point.

**Pull request merged**
